name: collage_result
description: A Flutter application for parsing and analyzing academic result PDFs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^6.1.2
  google_fonts: ^6.1.0
  go_router: ^14.0.0
  flutter_animate: ^4.5.0
  file_picker: ^8.1.7
  syncfusion_flutter_pdf: ^28.1.39
  excel: ^4.0.0
  path: ^1.9.1
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
